const GET_VIDEOGAMES = 'GET_VIDEOGAMES';
const GET_GENRES = 'GET_GENRES';
const FILTER_BY_GENRE = 'FILTER_BY_GENRE';
//const GET_VIDEOGAMES_NAME = 'GET_VIDEOGAMES_NAME';

export {
    GET_VIDEOGAMES,
    GET_GENRES,
    FILTER_BY_GENRE
    //GET_VIDEOGAMES_NAME
}